// ═══════════════════════════════════════════════════════════
//  INCOMPOL Web App — Engine Barrel
//  Single import point for ALL scheduling types + utilities.
//  Pure re-exports only — zero logic.
// ═══════════════════════════════════════════════════════════

// ── ALL types (canonical: domain/types/scheduling) ──
export type {
  ActionMessage,
  ActionMessagesSummary,
  AdvanceAction,
  AlternativeAction,
  ATCSParams,
  AutoReplanAction,
  AutoReplanConfig,
  AutoReplanResult,
  Block,
  CapacityLogEntry,
  ConstraintConfig,
  ConstraintMode,
  ConstraintName,
  CoverageAudit,
  CoverageAuditResult,
  CoverageAuditRow,
  CoverageCell,
  CoverageEntry,
  CoverageMatrixResult,
  CoverageMatrixSkuResult,
  CoverageSkuCell,
  CTPInput,
  CTPResult,
  CTPSkuInput,
  DayLoad,
  DayShiftCapacity,
  DayShiftStatus,
  DecisionEntry,
  DecisionKind,
  DecisionSeverity,
  DecisionSummary,
  DecisionType,
  DeficitEvolution,
  DispatchRule,
  EMachine,
  EngineData,
  EOp,
  ETool,
  FailureEvent,
  FailureJustification,
  FailureSeverity,
  FeasibilityReport,
  FullReplanInput,
  FullReplanResult,
  GridResult,
  ImpactedBlock,
  ImpactReport,
  InfeasibilityEntry,
  InfeasibilityReason,
  LaborWindow,
  LateDeliveryAnalysis,
  LateDeliveryEntry,
  MachineLoadEntry,
  MasterISOPData,
  MasterToolRecord,
  MatchUpInput,
  MatchUpResult,
  MoveAction,
  MoveableOp,
  MRPDayBucket,
  MRPRecord,
  MRPResult,
  MRPSkuRecord,
  MRPSkuSummary,
  MRPSkuViewRecord,
  MRPSkuViewResult,
  MRPSummary,
  NikufraCustomer,
  NikufraData,
  NikufraHistoryEvent,
  NikufraMachine,
  NikufraMOLoad,
  NikufraOperation,
  NikufraTool,
  ObjectiveWeights,
  OperationDeadline,
  OperationScore,
  OptimizationInput,
  OptimizationSetup,
  OptResult,
  OrderJustification,
  OvertimeAction,
  PartialReplanInput,
  PartialReplanResult,
  PlanningKPIs,
  PlanningMachine,
  PlanningOperation,
  PlanningTool,
  PlanState,
  QuickValidateResult,
  RCCPEntry,
  RemediationProposal,
  RemediationType,
  ReplanActionDetail,
  ReplanDispatchInput,
  ReplanDispatchResult,
  ReplanEventType,
  ReplanLayer,
  ReplanProposal,
  ReplanResult,
  ReplanSimulation,
  ReplanStrategyType,
  ResourceTimeline,
  RightShiftInput,
  RightShiftResult,
  RiskCell,
  RiskGridData,
  RiskLevel,
  RiskRow,
  RiskValidationInput,
  ROPConfig,
  ROPResult,
  ROPSkuResult,
  ROPSkuSummary,
  ROPSummary,
  SAConfig,
  SAInput,
  SAResult,
  ScheduleAllInput,
  ScheduleAllResult,
  ScheduleSlot,
  ScheduleValidationReport,
  ScheduleViolation,
  SchedulingConfig,
  SchedulingContext,
  SchedulingStrategy,
  ScoreWeights,
  ScoringJob,
  ServiceLevel,
  ShiftId,
  ShippingCutoffConfig,
  SplitAction,
  StartReason,
  SupplyPriority,
  SupplyPriorityConfig,
  TransformConfig,
  TransparencyReport,
  TwinAnomalyCode,
  TwinAnomalyEntry,
  TwinGroup,
  TwinOutput,
  TwinValidationInput,
  TwinValidationReport,
  UserReplanChoice,
  ValidationReport,
  Violation,
  ViolationSeverity,
  WhatIfDelta,
  WhatIfMutation,
  WhatIfResult,
  WorkContent,
  WorkforceConfig,
  WorkforceCoverageMissing,
  WorkforceDemandResult,
  WorkforceForecast,
  WorkforceForecastInput,
  WorkforceForecastWarning,
  WorkforceSuggestion,
  ZoneShiftDemand,
} from '../domain/types/scheduling';
// ── Defaults ──
export {
  createEmptyFeasibilityReport,
  DEFAULT_SCORE_WEIGHTS,
  finalizeFeasibilityReport,
} from '../domain/types/scheduling';
// ── Constants ──
export {
  DAY_CAP,
  DEFAULT_OEE,
  S0,
  S1,
  S2,
  T1,
} from '../domain/types/scheduling/constants';
export { DEFAULT_CONSTRAINT_CONFIG } from '../domain/types/scheduling/constraints';
// ── Legacy types (web-app specific) ──
export type {
  AreaCaps,
  Decision,
  ObjectiveProfile,
  OpDay,
} from '../domain/types/scheduling/legacy';
export { DEFAULT_SHIPPING_CUTOFF } from '../domain/types/scheduling/shipping';
export { DEFAULT_WORKFORCE_CONFIG } from '../domain/types/scheduling/workforce';
// ── Color bridge: C and TC resolve CSS vars ──
export { C, TC, tci } from '../theme/color-bridge';
export {
  getBlockProductionForOp,
  getBlockQtyForOp,
  getBlocksForOp,
} from '../utils/block-production';
// ── Pure functions (failures) ──
export {
  buildResourceTimelines,
  deriveLegacyStatus,
  getCapacityFactor,
  isFullyDown,
  legacyStatusToFailureEvents,
} from '../utils/failure-timeline';
// ── Pure utilities ──
export {
  fmtMin,
  fromAbs,
  getShift,
  getShiftEnd,
  getShiftStart,
  inferWorkdaysFromLabels,
  padMoArray,
  toAbs,
} from '../utils/format';
// ── Legacy helper ──
export { opsByDayFromWorkforce } from '../utils/workforce';
